/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.geo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the GeoLocations service. Represents a row in the &quot;rivetlogic_geo_GeoLocations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.geo.model.impl.GeoLocationsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.geo.model.impl.GeoLocationsImpl}.
 * </p>
 *
 * @author charles.rodriguez
 * @see GeoLocations
 * @see com.rivetlogic.geo.model.impl.GeoLocationsImpl
 * @see com.rivetlogic.geo.model.impl.GeoLocationsModelImpl
 * @generated
 */
public interface GeoLocationsModel extends BaseModel<GeoLocations> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a geo locations model instance should use the {@link GeoLocations} interface instead.
	 */

	/**
	 * Returns the primary key of this geo locations.
	 *
	 * @return the primary key of this geo locations
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this geo locations.
	 *
	 * @param primaryKey the primary key of this geo locations
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the geoname ID of this geo locations.
	 *
	 * @return the geoname ID of this geo locations
	 */
	public long getGeonameId();

	/**
	 * Sets the geoname ID of this geo locations.
	 *
	 * @param geonameId the geoname ID of this geo locations
	 */
	public void setGeonameId(long geonameId);

	/**
	 * Returns the country iso code of this geo locations.
	 *
	 * @return the country iso code of this geo locations
	 */
	@AutoEscape
	public String getCountryIsoCode();

	/**
	 * Sets the country iso code of this geo locations.
	 *
	 * @param countryIsoCode the country iso code of this geo locations
	 */
	public void setCountryIsoCode(String countryIsoCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GeoLocations geoLocations);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GeoLocations> toCacheModel();

	@Override
	public GeoLocations toEscapedModel();

	@Override
	public GeoLocations toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}