/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.geo.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rivetlogic.geo.model.GeoLocations;
import com.rivetlogic.geo.model.GeoLocationsModel;
import com.rivetlogic.geo.model.GeoLocationsSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the GeoLocations service. Represents a row in the &quot;rivetlogic_geo_GeoLocations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rivetlogic.geo.model.GeoLocationsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GeoLocationsImpl}.
 * </p>
 *
 * @author charles.rodriguez
 * @see GeoLocationsImpl
 * @see com.rivetlogic.geo.model.GeoLocations
 * @see com.rivetlogic.geo.model.GeoLocationsModel
 * @generated
 */
@JSON(strict = true)
public class GeoLocationsModelImpl extends BaseModelImpl<GeoLocations>
	implements GeoLocationsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a geo locations model instance should use the {@link com.rivetlogic.geo.model.GeoLocations} interface instead.
	 */
	public static final String TABLE_NAME = "rivetlogic_geo_GeoLocations";
	public static final Object[][] TABLE_COLUMNS = {
			{ "geonameId", Types.BIGINT },
			{ "countryIsoCode", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table rivetlogic_geo_GeoLocations (geonameId LONG not null primary key,countryIsoCode VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table rivetlogic_geo_GeoLocations";
	public static final String ORDER_BY_JPQL = " ORDER BY geoLocations.geonameId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY rivetlogic_geo_GeoLocations.geonameId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rivetlogic.geo.model.GeoLocations"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rivetlogic.geo.model.GeoLocations"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static GeoLocations toModel(GeoLocationsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GeoLocations model = new GeoLocationsImpl();

		model.setGeonameId(soapModel.getGeonameId());
		model.setCountryIsoCode(soapModel.getCountryIsoCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<GeoLocations> toModels(GeoLocationsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GeoLocations> models = new ArrayList<GeoLocations>(soapModels.length);

		for (GeoLocationsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rivetlogic.geo.model.GeoLocations"));

	public GeoLocationsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _geonameId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGeonameId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _geonameId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GeoLocations.class;
	}

	@Override
	public String getModelClassName() {
		return GeoLocations.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("geonameId", getGeonameId());
		attributes.put("countryIsoCode", getCountryIsoCode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long geonameId = (Long)attributes.get("geonameId");

		if (geonameId != null) {
			setGeonameId(geonameId);
		}

		String countryIsoCode = (String)attributes.get("countryIsoCode");

		if (countryIsoCode != null) {
			setCountryIsoCode(countryIsoCode);
		}
	}

	@JSON
	@Override
	public long getGeonameId() {
		return _geonameId;
	}

	@Override
	public void setGeonameId(long geonameId) {
		_geonameId = geonameId;
	}

	@JSON
	@Override
	public String getCountryIsoCode() {
		if (_countryIsoCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _countryIsoCode;
		}
	}

	@Override
	public void setCountryIsoCode(String countryIsoCode) {
		_countryIsoCode = countryIsoCode;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			GeoLocations.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GeoLocations toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GeoLocations)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GeoLocationsImpl geoLocationsImpl = new GeoLocationsImpl();

		geoLocationsImpl.setGeonameId(getGeonameId());
		geoLocationsImpl.setCountryIsoCode(getCountryIsoCode());

		geoLocationsImpl.resetOriginalValues();

		return geoLocationsImpl;
	}

	@Override
	public int compareTo(GeoLocations geoLocations) {
		long primaryKey = geoLocations.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GeoLocations)) {
			return false;
		}

		GeoLocations geoLocations = (GeoLocations)obj;

		long primaryKey = geoLocations.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<GeoLocations> toCacheModel() {
		GeoLocationsCacheModel geoLocationsCacheModel = new GeoLocationsCacheModel();

		geoLocationsCacheModel.geonameId = getGeonameId();

		geoLocationsCacheModel.countryIsoCode = getCountryIsoCode();

		String countryIsoCode = geoLocationsCacheModel.countryIsoCode;

		if ((countryIsoCode != null) && (countryIsoCode.length() == 0)) {
			geoLocationsCacheModel.countryIsoCode = null;
		}

		return geoLocationsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{geonameId=");
		sb.append(getGeonameId());
		sb.append(", countryIsoCode=");
		sb.append(getCountryIsoCode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.rivetlogic.geo.model.GeoLocations");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>geonameId</column-name><column-value><![CDATA[");
		sb.append(getGeonameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryIsoCode</column-name><column-value><![CDATA[");
		sb.append(getCountryIsoCode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GeoLocations.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GeoLocations.class
		};
	private long _geonameId;
	private String _countryIsoCode;
	private GeoLocations _escapedModel;
}